<?php
$data = [
  'A Little Bit',
  'Afternoon High',
  'And You Tell Me',
  'Angel In The Snow',
  'Barely Hanging On',
  'Between Your Mama And Yourself',
  'Blue Sky',
  'Cannot Hide',
  'Cold As Stone',
  'Cold River',
  'Cry Wolf',
  'Crying In The Rain',
  'Dark Is The Night For All',
  'Did Anyone Approach You',
  'Dragonfly',
  'Driftwood',
  'Early Morning',
  'East Of The Sun, West Of The Moon',
  'Forever Not Yours',
  'Heaven\'s Not For Saints',
  'Here I Stand And Face The Rain',
  'How Sweet It Was',
  'Hunting High And Low',
  'Hurry Home',
  'I Call Your Name',
  'I Dream Myself Alive',
  'I Wish I Cared',
  'I Won\'t Forget Her',
  'I\'ve Been Losing You',
  'Lamb To The Slaughter',
  'Less Than Pure',
  'Lie Down In Darkness',
  'Lifelines',
  'Little Black Heart',
  'Living A Boy\'s Adventure Tale',
  'Locust',
  'Love Is Reason',
  'Manhattan Skyline',
  'Mary Ellen Makes The Moment Count',
  'Maybe Maybe',
  'Memorial Beach',
  'Minor Earth Major Sky',
  'Move To Memphis',
  'October',
  'Oranges On Apple Trees',
  'Out Of Blue Comes Green',
  'Rolling Thunder',
  'Scoundrel Days',
  'Seemingly Nonstop July',
  'Shapes That Go Together',
  'Slender Frame',
  'Soft Rains Of April',
  'Solace',
  'Stay On These Roads',
  'Summer Moved On',
  'Sycamore Leaves',
  'Take On Me',
  'The Blood That Moves My Body',
  'The Blue Sky',
  'The Company Man',
  'The Living Daylights',
  'The Sun Always Shines On Tv',
  'The Sun Never Shone That Day',
  'The Swing Of Things',
  'The Way We Talk',
  'The Weight Of The Wind',
  'There\'s A Reason For It',
  'There\'s Never A Forever Thing',
  'This Alone Is Love',
  'Thought That It Was You',
  'Time And Again',
  'To Let You Win',
  'Touchy!',
  'Train Of Thought',
  'Turn The Lights Down',
  'Velvet',
  'Waiting For Her',
  'We\'re Looking For The Whales',
  'White Canvas',
  'X—mas Time (blows My Mind)',
  'You Are The One',
  'You Wanted More',
  'You\'ll End Up Crying',
  'You\'ll Never Get Over Me'
];

$query = $_GET['q'];

$matched = array_values(array_filter($data, function ($k) use ($query) {
  return stripos($k, $query) !== false;
}));

// Litt fake delay!
sleep(1);

echo json_encode($matched);
